/*
--Run First
CREATE SCHEMA STOCKOPTIONS;

--Run Third
CREATE TABLE STOCKOPTIONS.ACCOUNTS(
	Account_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Number VARCHAR(75) NOT NULL,
	Active INTEGER NOT NULL,
	Date_Opened DATE NOT NULL,
	Nickname VARCHAR(256),
	Account_Type VARCHAR(256),
	PRIMARY KEY(Number)
);

--Run Fourth
CREATE TABLE STOCKOPTIONS.STOCK(
	Stock_ID Integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Symbol VARCHAR(8) NOT NULL,
	Name VARCHAR(256) NOT NULL,
	Annual_Div_Rate FLOAT NOT NULL,
	Account INTEGER NOT NULL,
	Active BOOLEAN NOT NULL,
	PRIMARY KEY (Symbol, Account),
	FOREIGN KEY (Account) REFERENCES STOCKOPTIONS.ACCOUNTS (Account_ID)
);

--Run Fifth
CREATE TABLE STOCKOPTIONS.PRICES(
	Symbol VARCHAR(8) NOT NULL,
	Date DATE NOT NULL,
	Price DECIMAL(7,2),
	Price_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PRIMARY KEY (Symbol, Date, Price),
	FOREIGN KEY (SYMBOL) REFERENCES STOCKOPTIONS.STOCK (SYMBOL)
);

--Run Sixth
CREATE TABLE STOCKOPTIONS.TRANSACTIONS(
	Transaction_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Account_ID INTEGER NOT NULL,
	Stock_ID INTEGER NOT NULL,	
	Transaction_Type VARCHAR(75) NOT NULL,
	Date DATE NOT NULL,
	Shares INTEGER,
	Price DECIMAL(7,2),
	Total DECIMAL(11,2),
	Net DECIMAL(11,2),
	Commission DECIMAL(7,2),
	Expiration_Date DATE,
	Strike_Price DECIMAL(7,2),
	FOREIGN KEY (STOCK_ID) REFERENCES STOCKOPTIONS.STOCK (STOCK_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES STOCKOPTIONS.ACCOUNTS (ACCOUNT_ID)
);
--ALTER TABLE STOCKOPTIONS.STOCK ADD CONSTRAINT STOCK_ID UNIQUE (Stock_ID);


--These may or may not need to be run at all.
ALTER TABLE STOCKOPTIONS.STOCK ADD FOREIGN KEY (Account) REFERENCES STOCKOPTIONS.ACCOUNTS (Account_ID);
ALTER TABLE STOCKOPTIONS.ACCOUNTS ADD CONSTRAINT ACCOUNT_ID UNIQUE (Account_ID);
ALTER TABLE STOCKOPTIONS.ACCOUNT_TYPE ADD CONSTRAINT ACCOUNT_TYPE_ID UNIQUE (Account_Type_ID);
*/

--ALTER TABLE STOCKOPTIONS.TRANSACTIONS ADD FOREIGN KEY (Transaction_Type) REFERENCES STOCKOPTIONS.TRANSACTION_TYPE (Transasction_Type_ID);
--ALTER TABLE STOCKOPTIONS.TRANSACTIONS ADD COLUMN Account INTEGER NOT NULL DEFAULT 0;
--ALTER TABLE STOCKOPTIONS.TRANSACTION_TYPE ADD CONSTRAINT TRANSACTION_TYPE_ID UNIQUE (Transaction_Type_ID);

DELETE FROM STOCKOPTIONS.PRICES;
DELETE FROM STOCKOPTIONS.TRANSACTIONS;
DELETE FROM STOCKOPTIONS.STOCK;
DELETE FROM STOCKOPTIONS.ACCOUNTS;
DELETE FROM STOCKOPTIONS.ACCOUNT_TYPE;

INSERT INTO STOCKOPTIONS.ACCOUNT_TYPE (Account_Type) VALUES ('Joint'), ('Personal'), ('IRA');
INSERT INTO STOCKOPTIONS.ACCOUNTS (Number, Nickname, Date_Opened, Account_Type, Active)
	VALUES ('TST1', 'Test Account 1', '2016-09-11', 5932, 1),
		('TST2', 'Test Account 2', '2016-10-12', 5933, 1);
INSERT INTO STOCKOPTIONS.STOCK (Symbol, Name, Account, Annual_Div_Rate, Active)
	VALUES('AMZN', 'Amazon.com, Inc.', 5924, 0.25, 1),
		('NKE', 'Nike Inc.', 5925, 0.36, 1);
INSERT INTO STOCKOPTIONS.TRANSACTIONS (Symbol, Account, Date, Price, Net, Commission, Transaction_Type)
	VALUES ('NKE', 4622, '2016-11-25', 34.23, 345.43, 2.34, 'Sale'),
		('NKE', 4622, '2016-12-31', 43.54, 2343.23, 0.00, 'Purchase'),
		('AMZN', 4621, '2015-01-04', 23.43, 23.43, 12.33, 'Sale'),
		('AMZN', 4621, '2013-08-23', 23.56, 21.23, 0.00, 'Purchase');
		
SELECT * FROM STOCKOPTIONS.ACCOUNTS;
SELECT * FROM STOCKOPTIONS.PRICES;
SELECT * FROM STOCKOPTIONS.STOCK;
SELECT * FROM STOCKOPTIONS.TRANSACTIONS;


SELECT Symbol, Name, Annual_Div_Rate, STOCKOPTIONS.ACCOUNTS.Number, STOCKOPTIONS.STOCK.Active
FROM STOCKOPTIONS.STOCK
JOIN STOCKOPTIONS.ACCOUNTS
ON STOCKOPTIONS.STOCK.Account = STOCKOPTIONS.ACCOUNTS.Account_ID;

SELECT Transaction_ID, Symbol, STOCKOPTIONS.ACCOUNTS.Number, Date, Price, Net, Commission, Transaction_Type
FROM STOCKOPTIONS.TRANSACTIONS
JOIN STOCKOPTIONS.ACCOUNTS
ON STOCKOPTIONS.TRANSACTIONS.Account = STOCKOPTIONS.ACCOUNTS.Account_ID
WHERE Symbol = 'NKE'
ORDER BY Date DESC;

SELECT * FROM STOCKOPTIONS.TRANSACTIONS
WHERE Symbol = 'NFLX'
ORDER BY Transaction_Type, Date DESC;

--DROP TABLE STOCKOPTIONS.ACCOUNTS;
--DROP TABLE STOCKOPTIONS.STOCK;
--DROP TABLE STOCKOPTIONS.TRANSACTIONS;
--DROP TABLE STOCKOPTIONS.ACCOUNT_TYPE;
--DROP TABLE STOCKOPTIONS.PRICES;

/*SET SCHEMA STOCKOPTIONS;
SELECT Account_ID, Number, Nickname, STOCKOPTIONS.ACCOUNT_TYPE.Account_Type, Date_Opened, Active 
FROM STOCKOPTIONS.ACCOUNTS
JOIN STOCKOPTIONS.ACCOUNT_TYPE AS Account_Type
ON STOCKOPTIONS.ACCOUNTS.ACCOUNT_TYPE = STOCKOPTIONS.ACCOUNT_TYPE.ACCOUNT_TYPE_ID;*/