/*CREATE SCHEMA STOCKOPTIONS;

CREATE TABLE STOCKOPTIONS.STOCK(
	Symbol VARCHAR(8) NOT NULL,
	Name VARCHAR(256) NOT NULL,
	Annual_Div_Rate FLOAT NOT NULL,
	Account INTEGER NOT NULL,
	Active INTEGER NOT NULL,
	PRIMARY KEY (Symbol)
);

CREATE TABLE STOCKOPTIONS.PRICES(
	Symbol VARCHAR(8) NOT NULL,
	Date DATE NOT NULL,
	Price DECIMAL(7,2),
	Price_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PRIMARY KEY (Symbol, Date, Price),
	FOREIGN KEY (SYMBOL) REFERENCES STOCKOPTIONS.STOCK (SYMBOL)
);

CREATE TABLE STOCKOPTIONS.TRANSACTIONS(
	Symbol VARCHAR(8) NOT NULL,
	Date DATE NOT NULL,
	Action INTEGER NOT NULL,
	Price DECIMAL(7,2),
	Net DECIMAL(8,2),
	Transaction_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PRIMARY KEY(Symbol, Date, Action, Price),
	FOREIGN KEY (SYMBOL) REFERENCES STOCKOPTIONS.STOCK (SYMBOL)
);*/

ALTER TABLE STOCKOPTIONS.PRICES ADD COLUMN Price_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1);

alter table stockoptions.prices drop column price_id;

DELETE FROM STOCKOPTIONS.PRICES;

DELETE FROM STOCKOPTIONS.TRANSACTIONS;
DELETE FROM STOCKOPTIONS.STOCK;

INSERT INTO STOCKOPTIONS.STOCK VALUES('AMZN', 'Amazon.com, Inc.', 0.25, 1);

SELECT * FROM STOCKOPTIONS.PRICES;
SELECT * FROM STOCKOPTIONS.STOCK;

SELECT * FROM STOCKOPTIONS.PRICES WHERE Symbol = 'NFLX' ORDER BY Date DESC;